name = "track"
keep_vars = true
main = "src/index.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "track.lixo.in/*", zone_name = "lixo.in" }
  ]

[env.production]
vars = { ZOHO_BASE_URL = "https://www.zohoapis.in", ZOHO_ACCOUNTS_URL = "https://accounts.zoho.in", ZOHO_WRITEBACK = "true" }

[triggers]
crons = []
